export const NOTE_CONSTANTS = {
  GET_PAGINATED_NOTES: "GET_PAGINATED_NOTES",
  INFINITE_QUERY: "INFINITE_QUERY",
  GET_NOTE_BY_ID: "GET_NOTE_BY_ID",
  GET_NOTE_BY_COMPOSER_ID: "GET_NOTE_BY_COMPOSER_ID",
};
